In [2]:
import torch

In [3]:
# define activation function
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [4]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [7]:
# Calculate output
# np.dot <=> torch.matmul or torch.mm
# for transpose => object.reshape(a,b) : return new tensor, as in it copies data to another part of memory
# for transpose => object.resize_(a,b) : returns the same tensor with a different shape. However, if the new shape results in fewer elements than the original tensor, some elements will be removed from the tensor (but not from memory).
# Here I should note that the underscore at the end of the method denotes that this method is performed in-place.
# for transpose => object.view(a,b) : will return a new tensor with the same data as weights with size (a,b)
# https://discuss.pytorch.org/t/what-is-in-place-operation/16244

# using sum
print(activation((features * weights).sum() + bias))
# using torch.mm
print(activation(torch.mm(features, weights.view(5,1)) + bias))

tensor([[0.1595]])
tensor([[0.1595]])


In [8]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [15]:
value_ith = activation(torch.mm(features, W1) + B1)
res_hto = activation(torch.mm(value_ith, W2) + B2)
res_hto

tensor([[0.3171]])

In [17]:
# numpy - torch.tensor
import numpy as np
a = np.random.rand(4,3)

In [19]:
b = torch.from_numpy(a)

In [20]:
b

tensor([[0.3253, 0.7865, 0.7163],
        [0.5673, 0.8860, 0.4592],
        [0.2449, 0.6925, 0.2486],
        [0.6354, 0.5284, 0.9344]], dtype=torch.float64)

In [21]:
b.mul_(2)

tensor([[0.6506, 1.5730, 1.4326],
        [1.1346, 1.7720, 0.9185],
        [0.4898, 1.3850, 0.4973],
        [1.2708, 1.0569, 1.8689]], dtype=torch.float64)

In [22]:
a

array([[0.65064969, 1.57301207, 1.43264714],
       [1.13459218, 1.77197977, 0.91846448],
       [0.48977678, 1.384985  , 0.49728394],
       [1.27078262, 1.05688096, 1.86888358]])